name: Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
      version:
        description: 'Version tag to deploy'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run for prod
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: echo "Deploying to production"

      - name: Run for staging
        if: ${{ github.event.inputs.environment == 'staging'}}
        run: echo "Deploying to staging"
